spring:
  jpa:
    hibernate:
      ddl-auto: create


taller:
  spring:
    ua:
      aulas:
        - "L26"
        - "L27"
        - "L28"
server:
  port: 9081


managment:
  segurity:
    enabled: false

security:
  user:
    name: user
    password: pass